### ISSUE TITLE
出現錯誤訊息

### ISSUE THREAD

**Issue by jandacreate** [jun-lu/react-webpack-example#3]
npm run dist 後 上傳到server
跑起來會出現以下訊息~

Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.

謝謝喔

**Comment by jun-lu** [comment]
非常感谢你的反馈，以上问题的解决办法是
修改webpack.config.js中 135 行的代码块如下

````

//线上打包需要压缩代码
if(dist_environment != -1){
	config.plugins.unshift(
		new webpack.optimize.UglifyJsPlugin({
        compress: {
            warnings: false
        }
    }),
		new webpack.DefinePlugin({
      'process.env':{
        'NODE_ENV': JSON.stringify('production')
      }
    })
  )
}


````

添加了  new webpack.DefinePlugin  的配置.
最新的master分支已包含此更新
